apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: mongo-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeMode: Filesystem
  resources:
    requests:
      storage: 500Mi
  selector:
    matchLabels:
      role: database
