apiVersion: v1
kind: Service
metadata:
  name: crypto-service
spec:
  type: NodePort
  selector:
    app: crypto-file-api
  ports:
    - protocol: TCP
      port: 7080
      targetPort: porta-crypto
  