apiVersion: v1
kind: Pod
metadata:
  name: api-pod
  labels:
    app: "simple-api"
spec:
  containers:
    - name: simple-api
      image: kircy/simple-node-api
      env:
        - name: PORT
          value: "8080"
      ports:
        - containerPort: 8080
          name: porta-api
      volumeMounts:
        - name: volume-simple-api
          mountPath: /usr/src/app
  volumes:
    - name: volume-simple-api
      hostPath: 
         path: /data
         type: Directory
# To acess port-forward use this:
# kubectl port-forward svc/pod-api-svc 8085